// src/constants/notificationTypes.ts
export const NOTIFICATION_TYPES = {
  BUS_DELAYED: "BUS_DELAYED",
  BUS_ARRIVING: "BUS_ARRIVING",
  BUS_NEARBY: "BUS_NEARBY",
  BUS_CANCELLED: "BUS_CANCELLED",
  NEXT_STOP: "NEXT_STOP",
  TRIP_STARTED: "TRIP_STARTED",
  TRIP_ENDED: "TRIP_ENDED",
  EMERGENCY_ALERT: "EMERGENCY_ALERT",
  ROUTE_CHANGE: "ROUTE_CHANGE",
  GENERAL_ANNOUNCEMENT: "GENERAL_ANNOUNCEMENT",
};
