export const kkrKsrTransportData = {
  collegeName: "KKR & KSR INSTITUTE OF TECHNOLOGY AND SCIENCES",
  location: "VINJANAMPADU, GUNTUR-17",
  routes: [
    {
      busNumber: "01A",
      routeName: "SVN COLONY-STAMBALAGARUVU",
      stops: [
        "SVN COLONY TEMPLE",
        "SVN COLONY 4TH LINE",
        "SVN COLONY ARCH",
        "GUJJANAGUNDLA CENTRE",
        "MARUTHI NAGAR",
        "HANUMAIAH COMPANY",
        "STAMBALA GARUVU",
      ],
    },
    {
      busNumber: "01B",
      routeName: "PALAKALURU-REGISTER OFFICE",
      stops: [
        "PALAKALUR",
        "RATNAGIRI COLONY",
        "OLD RTO OFFICE",
        "PATTABHI PURAM",
        "SWAMY THEATRE",
        "TJPS COLLEGE",
        "REGISTER OFFICE",
      ],
    },
    {
      busNumber: "01C",
      routeName: "TJPS COLLEGE-NALLACHERUVU",
      stops: [
        "TJPS COLLEGE",
        "REGISTER OFFICE",
        "DISTRICT COURT",
        "NAGARAM PALEM (3 BOMMALA CENTRE)",
        "YETTU ROAD",
        "NALLACHERUVU",
      ],
    },
    {
      busNumber: "02A",
      routeName: "STAMBALAGARUVU WATERTANK-AYYAPPA SWAMY TEMPLE",
      stops: [
        "STAMBALA GARUVU WATER TANKS",
        "RAJENDRA NAGAR",
        "CHANDRA GAS COMPANY",
        "SPENCERS",
        "AYYAPPA SWAMY TEMPLE",
      ],
    },
    {
      busNumber: "02B",
      routeName: "GARDENS-BAKER FUN",
      stops: [
        "BRUNDAVAN GARDENS CENTRE",
        "SEETHARAMAIAH HIGH SCHOOL",
        "NAYAR HOTEL",
        "BAKERS FUN",
      ],
    },
    {
      busNumber: "02C",
      routeName: "HDFC BANK-HOLLY WOOD & BOLLY WOOD",
      stops: [
        "HDFC BANK",
        "SONO VISION",
        "UNION BANK",
        "HOLLY WOOD & BOLLY WOOD",
      ],
    },
    {
      busNumber: "03A",
      routeName: "SWARNA BAHARTHI NAGAR-SAIBABA ROAD",
      stops: [
        "SWARNA BARATHI NAGAR",
        "JKC COLLEGE ROAD",
        "SIDDARTHA NAGAR ARCH",
        "CHALAPATHI GROUNDS",
        "NAVABHARAT NAGAR GUEST HOUSE",
        "VIDYA NAGAR 1ST LINE",
        "DON BOSCO",
        "SAI BABA ROAD",
      ],
    },
    {
      busNumber: "03B",
      routeName: "CHANDRAMOULI NAGAR POSTOFFICE-HARIHARAMAHAL",
      stops: [
        "CHANDRAMOULI NAGAR 1ST LINE",
        "KOLLA PHARAM",
        "LIBRARY CENTRE",
        "KORETIPADU GANDHI BOMMA",
        "KORETIPADU MARKET",
        "HARI HARA MAHAL",
      ],
    },
    {
      busNumber: "04A",
      routeName: "GORANTLA-NAGARALU",
      stops: ["GORANTLA", "NAGARALU"],
    },
    {
      busNumber: "04B",
      routeName: "MEDICAL HOSTEL-LODGE CENTRE",
      stops: [
        "MEDICAL HOSTEL",
        "HINDU COLLEGE PHARMACY",
        "ANJANEYA SWAMY TEMPLE",
        "ALA HOSPITAL",
        "SBI",
        "LODGE CENTRE",
      ],
    },
    {
      busNumber: "04C",
      routeName: "TALUKA CENTRE-MARKET",
      stops: ["TALUKA CENTRE", "SANKARVILAS CENTRE", "MARKET"],
    },
    {
      busNumber: "04D",
      routeName: "BRODIPET-MARKET",
      stops: ["BRODIPET 4/17", "SANKARVILAS CENTRE", "MARKET"],
    },
    {
      busNumber: "05A",
      routeName: "NAAZ CENTRE-BUS STAND",
      stops: [
        "NAAZ CENTRE",
        "KOTHAPETA SIVALAYAM",
        "MANIPURAM BRIDGE",
        "BUS STAND",
        "CHANDANA BROTHER/OLD BUS STAND",
      ],
    },
    {
      busNumber: "05B",
      routeName: "BR STADIUM-SANGADIGUNTA",
      stops: [
        "MANI HOTEL",
        "BR STADIUM",
        "ANAND PETA",
        "REDDLA BAZAR",
        "SANGADIGUNTA",
        "HUSSAIN NAGAR",
        "ANDHRA MUSLIM COLLEGE",
      ],
    },
    {
      busNumber: "10A/10B",
      routeName: "VIJAYAWADA-GNT",
      stops: [
        "VIJAYAWADA",
        "TEADEPALLI",
        "MANGALAGIRI PATHA BUS STAND",
        "CHINNA KAKANI",
        "NAMBURU CROSS ROAD",
        "SANKAR EYE HOSPITAL",
      ],
    },
    {
      busNumber: "15A/15B",
      routeName: "MARTURU-GNT",
      stops: [
        "MARTURU",
        "CHILAKALURIPETA",
        "YEDLAPADU",
        "CHOWDAVARAM",
        "POTHURU",
        "ETUKURU",
      ],
    },
    {
      busNumber: "17A/17B",
      routeName: "SATTENAPALLI-PERECHARLA",
      stops: [
        "SATTENAPALLI",
        "KANTEPUDI",
        "PALADUGU CROSS ROAD",
        "MEDIKONDURU",
      ],
    },
    {
      busNumber: "18A/18B",
      routeName: "AMARAVATHI-CHILLIS",
      stops: [
        "AMARAVATHI",
        "DHARANIKOTA",
        "LEMALLE CENTRE",
        "MOTHADAKA",
        "LAM",
        "GORANTLA",
        "CHILLIS",
      ],
    },
    {
      busNumber: "Hostels",
      routeName: "HOSTEL ROUTES",
      stops: ["GIRLS HOSTEL", "KITS BOYS HOSTEL-1"],
    },
  ],
};
