// Mocks generated by Mockito 5.4.6 from annotations
// in collegebus/test/transactions_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:collegebus/core/constants/constants.dart' as _i9;
import 'package:collegebus/features/audit/domain/audit_log_model.dart' as _i3;
import 'package:collegebus/features/college/domain/college_model.dart' as _i4;
import 'package:collegebus/features/payment/domain/transaction_model.dart'
    as _i7;
import 'package:collegebus/features/sos/domain/sos_model.dart' as _i6;
import 'package:collegebus/features/super_admin/services/super_admin_service.dart'
    as _i2;
import 'package:collegebus/features/user/domain/user_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SuperAdminService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuperAdminService extends _i1.Mock implements _i2.SuperAdminService {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.AuditLogModel> get auditLogs =>
      (super.noSuchMethod(
            Invocation.getter(#auditLogs),
            returnValue: <_i3.AuditLogModel>[],
            returnValueForMissingStub: <_i3.AuditLogModel>[],
          )
          as List<_i3.AuditLogModel>);

  @override
  List<_i4.CollegeModel> get colleges =>
      (super.noSuchMethod(
            Invocation.getter(#colleges),
            returnValue: <_i4.CollegeModel>[],
            returnValueForMissingStub: <_i4.CollegeModel>[],
          )
          as List<_i4.CollegeModel>);

  @override
  List<_i5.UserModel> get globalUsers =>
      (super.noSuchMethod(
            Invocation.getter(#globalUsers),
            returnValue: <_i5.UserModel>[],
            returnValueForMissingStub: <_i5.UserModel>[],
          )
          as List<_i5.UserModel>);

  @override
  List<_i6.SosModel> get sosLogs =>
      (super.noSuchMethod(
            Invocation.getter(#sosLogs),
            returnValue: <_i6.SosModel>[],
            returnValueForMissingStub: <_i6.SosModel>[],
          )
          as List<_i6.SosModel>);

  @override
  List<_i6.SosModel> get globalActiveSos =>
      (super.noSuchMethod(
            Invocation.getter(#globalActiveSos),
            returnValue: <_i6.SosModel>[],
            returnValueForMissingStub: <_i6.SosModel>[],
          )
          as List<_i6.SosModel>);

  @override
  List<_i7.TransactionModel> get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: <_i7.TransactionModel>[],
            returnValueForMissingStub: <_i7.TransactionModel>[],
          )
          as List<_i7.TransactionModel>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> loadSystemDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#loadSystemDashboard, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> verifyCollege(String? collegeId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCollege, [collegeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> suspendCollege(String? collegeId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#suspendCollege, [collegeId, reason]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleMaintenance(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleMaintenance, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateCollege(
    String? collegeId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCollege, [collegeId, data]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserRole(String? userId, _i9.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [userId, role]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearSystemLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearSystemLogs, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchTransactions({
    String? plan,
    DateTime? startDate,
    DateTime? endDate,
    String? collegeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, [], {
              #plan: plan,
              #startDate: startDate,
              #endDate: endDate,
              #collegeId: collegeId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
