export const collegesData = [
  {
    name: "KKR & KSR INSTITUTE OF TECHNOLOGY AND SCIENCES",
    domain: "kkr.ac.in",
    shortName: "KKR",
    routes: [
      {
        busNumber: "01A",
        routeName: "SVN COLONY-STAMBALAGARUVU",
        stops: [
          "SVN COLONY TEMPLE",
          "SVN COLONY 4TH LINE",
          "SVN COLONY ARCH",
          "GUJJANAGUNDLA CENTRE",
          "MARUTHI NAGAR",
          "HANUMAIAH COMPANY",
          "STAMBALA GARUVU",
        ],
      },
      {
        busNumber: "01B",
        routeName: "PALAKALURU-REGISTER OFFICE",
        stops: [
          "PALAKALUR",
          "RATNAGIRI COLONY",
          "OLD RTO OFFICE",
          "PATTABHI PURAM",
          "SWAMY THEATRE",
          "TJPS COLLEGE",
          "REGISTER OFFICE",
        ],
      },
      {
        busNumber: "01C",
        routeName: "TJPS COLLEGE-NALLACHERUVU",
        stops: [
          "TJPS COLLEGE",
          "REGISTER OFFICE",
          "DISTRICT COURT",
          "NAGARAM PALEM (3 BOMMALA CENTRE)",
          "YETTU ROAD",
          "NALLACHERUVU",
        ],
      },
      {
        busNumber: "02A",
        routeName: "STAMBALAGARUVU WATERTANK - AYYAPPA SWAMY TEMPLE",
        stops: [
          "STAMBALA GARUVU WATER TANKS",
          "RAJENDRA NAGAR",
          "CHANDRA GAS COMPANY",
          "SPENCERS",
          "AYYAPPA SWAMY TEMPLE",
        ],
      },
      {
        busNumber: "02B",
        routeName: "GARDENS-BAKER FUN",
        stops: [
          "BRUNDAVAN GARDENS CENTRE",
          "SEETHARAMAIAH HIGH SCHOOL",
          "NAYAR HOTEL",
          "BAKERS FUN",
        ],
      },
      {
        busNumber: "02C",
        routeName: "HDFC BANK-HOLLY WOOD & BOLLY WOOD",
        stops: [
          "HDFC BANK",
          "SONO VISION",
          "UNION BANK",
          "HOLLY WOOD & BOLLY WOOD",
        ],
      },
      {
        busNumber: "03A",
        routeName: "SWARNA BAHARTHI NAGAR - SAIBABA ROAD",
        stops: [
          "SWARNA BARATHI NAGAR",
          "JKC COLLEGE ROAD",
          "SIDDARTHA NAGAR ARCH",
          "CHALAPATHI GROUNDS",
          "NAVABHARAT NAGAR GUEST HOUSE",
          "VIDYA NAGAR 1ST LINE",
          "DON BOSCO",
          "SAI BABA ROAD",
        ],
      },
      {
        busNumber: "03B",
        routeName: "CHANDRAMOULI NAGAR POSTOFFICE-HARIHARAMAHAL",
        stops: [
          "CHANDRAMOULI NAGAR 1ST LINE",
          "KOLLA PHARAM",
          "LIBRARY CENTRE",
          "KORETIPADU GANDHI BOΜΜΑ",
          "KORETIPADU MARKET",
          "HARI HARA MAHAL",
        ],
      },
      {
        busNumber: "04A",
        routeName: "GORANTLA-NAGARALU",
        stops: ["GORANTLA", "NAGARALU"],
      },
      {
        busNumber: "04B",
        routeName: "MEDICAL HOSTEL - LODGE CENTRE",
        stops: [
          "MEDICAL HOSTEL",
          "HINDU COLLEGE PHARMACY",
          "ANJANEYA SWAMY TEMPLE",
          "ALA HOSPITAL",
          "SATRAM",
          "SBI",
          "LODGE CENTRE",
        ],
      },
      {
        busNumber: "04C",
        routeName: "TALUKA CENTRE-MARKET",
        stops: ["TALUKA CENTRE", "SANKARVILAS CENTRE", "MARKET"],
      },
      {
        busNumber: "04D",
        routeName: "BRODIPET-MARKET",
        stops: [
          "BRODIPET 4/17",
          "TALUKA CENTRE",
          "SANKARVILAS CENTRE",
          "MARKET",
        ],
      },
      {
        busNumber: "05A",
        routeName: "NAAZ CENTRE-BUS STAND",
        stops: [
          "NAAZ CENTRE",
          "KOTHAPETA SIVALAYAM",
          "MANIPURAM BRIDGE",
          "BUS STAND",
          "CHANDANA BROTHER/OLD BUS STAND",
        ],
      },
      {
        busNumber: "05B",
        routeName: "BR STADIUM-SANGADIGUNTA",
        stops: [
          "BR STADIUM",
          "ANAND PETA",
          "REDDLA BAZAR",
          "SANGADIGUNTA",
          "HUSSAIN NAGAR",
          "ANDHRA MUSLIM COLLEGE",
          "CHANDRABABU NAIDU COLONY",
        ],
      },
      {
        busNumber: "05C",
        routeName: "SANGADIGUNTA-AMMAVARI TEMPLE-ETUKURU RD",
        stops: [
          "SANGADIGUNTA-AMMAVARI TEMPLE",
          "LANCHSTER ROAD",
          "ETUKURU BUS STAND",
          "CHAKALI GUNTA",
        ],
      },
      {
        busNumber: "06A",
        routeName: "SYAMALA NAGAR AT AGRAHARAM",
        stops: [
          "SYAMALA NAGAR 8TH LINE",
          "SYAMALA NAGAR 4TH LINE",
          "RECRUITMENT OFFICE",
          "RAILWAY GATE",
          "AT AGRAHARAM O LINE",
          "AT AGRAHARAM 4TH LINE",
          "BORING CENTRE",
          "AMMAVARI TEMPLE",
        ],
      },
      {
        busNumber: "06B",
        routeName: "CHUTTUGUNTA-NALLACHERUVU",
        stops: [
          "VENKATAPPAIAH COLONY",
          "CHUTTUGUNTA",
          "SUBHANI HOTEL",
          "ITC",
          "ANDHRA BANK",
          "NALLA CHERUVU",
        ],
      },
      {
        busNumber: "07A",
        routeName: "GIRLS HOSTEL - KAMMA HOSTEL -1",
        stops: ["GIRLS HOSTEL", "KAMMA HOSTEL"],
      },
      {
        busNumber: "08A",
        routeName: "KITS BOYS HOSTEL-1",
        stops: ["BOYS HOSTEL"],
      },
      {
        busNumber: "09A",
        routeName: "INNER RING ROAD-MANIPURAM BRIDGE",
        stops: [
          "RAILWAY GATE IRR",
          "GATTIPADU",
          "AMMAVARI TEMPLE",
          "VASAVI COMPLEX",
          "RTC COLONY",
          "BR STADIUM",
          "OLD BUS STAND",
        ],
      },
      {
        busNumber: "10A/B",
        routeName: "VIJAYAWADA-GUNTUR",
        stops: [
          "VIJAYAWADA",
          "TEADEPALLI",
          "MANGALAGIRI PATHA BUS STAND",
          "TENALI ROAD",
          "MASJID CENTRE",
          "CHINNA KAKANI",
          "KAJA",
          "KOPPURAVURU CROSS ROAD",
          "NAMBURU CROSS ROAD",
          "SANKAR EYE HOSPITAL",
        ],
      },
    ],
  },
  {
    name: "VIGNAN'S NIRULA INSTITUTE OF TECHNOLOGY AND SCIENCES FOR WOMEN",
    domain: "vignannirula.ac.in",
    shortName: "VIGNAN",
    routes: [
      {
        busNumber: "VGN-01",
        routeName: "BRODIPET-LODGE CENTRE",
        stops: ["BRODIPET 4TH LINE", "LODGE CENTRE"],
      },
      {
        busNumber: "VGN-02",
        routeName: "GORANTLA-NAAZ CENTRE",
        stops: ["GORANTLA CENTRE", "NAAZ CENTRE"],
      },
    ],
  },
  {
    name: "RVR & JC COLLEGE OF ENGINEERING",
    domain: "rvrjcce.ac.in",
    shortName: "RVR",
    routes: [
      {
        busNumber: "RVR-01",
        routeName: "CHOWDAVARAM-GUNTUR",
        stops: ["CHOWDAVARAM", "POTHURU", "GUNTUR BUS STAND"],
      },
      {
        busNumber: "RVR-02",
        routeName: "SATTENAPALLI-PERECHARLA",
        stops: ["SATTENAPALLI", "MEDIKONDURU", "PERECHARLA"],
      },
    ],
  },
];
